# Generated by Django 5.1.4 on 2026-08-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangerZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('zone_type', models.CharField(choices=[('landslide', 'Landslide'), ('fog', 'Fog'), ('flood', 'Flood'), ('death', 'High Death Zone'), ('traffic', 'Heavy Traffic'), ('snow', 'Snow/Avalanche')], max_length=50)),
                ('label', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
            ],
        ),
    ]
